/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const VolunteerApplication = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'interestArea' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllVolunteerApplications' : IDL.Func(
      [],
      [IDL.Vec(VolunteerApplication)],
      ['query'],
    ),
  'getContactMessageByEmail' : IDL.Func(
      [IDL.Text],
      [ContactMessage],
      ['query'],
    ),
  'getVolunteerApplicationByEmail' : IDL.Func(
      [IDL.Text],
      [VolunteerApplication],
      ['query'],
    ),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitVolunteerApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const VolunteerApplication = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'interestArea' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllVolunteerApplications' : IDL.Func(
        [],
        [IDL.Vec(VolunteerApplication)],
        ['query'],
      ),
    'getContactMessageByEmail' : IDL.Func(
        [IDL.Text],
        [ContactMessage],
        ['query'],
      ),
    'getVolunteerApplicationByEmail' : IDL.Func(
        [IDL.Text],
        [VolunteerApplication],
        ['query'],
      ),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitVolunteerApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };